### ISSUE TITLE
Biblioteca de funções pre-definidas

### ISSUE THREAD

**Issue by rbonifacio** [UnBCIC-TP2/Oberon-Scala#46]
Implementar um módulo Oberon com um conjunto de funções pre-definidas. A especificação da linguagem lista essas funções que devem estar disponíveis em qualquer implementação da linguagem Oberon.

**Comment by rafaelcn** [comment]
Professor, na especificação eu não encontrei as funções que devem estar disponíveis no escopo global de qualquer módulo. Nessa esteira, eu gostaria de implementar essa funcionalidade junto a meu grupo (G7).

**Comment by rafaelcn** [comment]
Após uma olhada mais profunda eu as encontrei. Segue anexo das funções que deverão ser implementadas. Seria interessante editar essa issue para contemplar essas funções.

![image](https://user-images.githubusercontent.com/3271143/109666617-1979a480-7b4e-11eb-8786-8caca24b50b3.png)
![image](https://user-images.githubusercontent.com/3271143/109666686-2ac2b100-7b4e-11eb-8fc2-ddee1d1432a6.png)

**Comment by rafaelcn** [comment]
Vamos fechar um escopo de funções da biblioteca padrão de Oberon:

- [ ] Write
- [ ] Writeln
- [ ] ReadInt
- [ ] Abs
- [ ] Odd
- [ ] Lsl
- [ ] Asr
- [ ] Inc (com sobrecarga inclusive)

Esse conjunto de funções parece ser interessante para o grupo G7 implementar (falei com todos aqui do grupo).
