### ISSUE TITLE
Proposta de mudança na arquitetura de statements

### ISSUE THREAD

**Issue by rafaelcn** [UnBCIC-TP2/Oberon-Scala#47]
Eu percebi que todas as _statements_, ou _stmts_, estão definidas em um único arquivo ([Interpreter](https://github.com/UnBCIC-TP2/Oberon-Scala/blob/master/src/main/scala/br/unb/cic/oberon/interpreter/Interpreter.scala)). No entanto, qualquer alteração na interpretação desses _stmts_ ou na inclusão de algum recurso do interpretador vai acabar fazendo com que aquele arquivo fique muito grande.

Proponho a separação desse conjunto de _stmts_, um para cada arquivo onde cada _stmt_ é uma classe. Essa proposta contém benefícios a longo prazo e é simular a alguns compiladores como o [brain](https://github.com/brain-labs/brain/tree/master/src/ast/instr).

**Comment by rbonifacio** [comment]
@rafaelcn , os statements estão definidos como uma hierarquia de classes na [AST](https://github.com/UnBCIC-TP2/Oberon-Scala/blob/ed15cc247cff25a790ed400b2c753b8a08759c51/src/main/scala/br/unb/cic/oberon/ast/OberonModule.scala#L72-L89). 

Estamos explorando recursos de linguagens imperativas (OO) e recursos de linguagens funcionais. Na minha experiência, nos beneficiamos muito de casamento de padrões nas implementações de linguagens de programação. Em particular, poderíamos estar usando apenas casamento de padrões para implementar o Interpretador (por exemplo). A opção por uma abordagem híbrida (visitor + pattern matching) tem por finalidade discutir padrões de projeto com os alunos. Na prática, faria uma implementação mais alinhada com o paradigma funcional---i.e., sem os visitors.

**Comment by rafaelcn** [comment]
Como discutido em aula, concordo com seus pontos.
